# Generated by Django 5.0 on 2024-11-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_fname', models.CharField(max_length=50)),
                ('act_iname', models.CharField(max_length=50)),
                ('act_gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_fname', models.CharField(max_length=50)),
                ('dir_iname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('time', models.IntegerField()),
                ('lang', models.CharField(max_length=50)),
                ('dt_rel', models.DateField(auto_now=True)),
                ('rel_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.actor')),
                ('mov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.director')),
                ('mov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.genres')),
                ('mov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_starts', models.IntegerField()),
                ('num_o_ratings', models.IntegerField()),
                ('mov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.movie')),
                ('rev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.reviewer')),
            ],
        ),
    ]
