# Generated by Django 5.0 on 2024-12-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
