# Generated by Django 5.0 on 2024-12-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_actor_deleted_at_actor_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.actor')),
            ],
            bases=('apis.actor',),
        ),
    ]
